baseURL = "https://jpcerezo.info/"
languageCode = "en-us"
title = "ESNOG | Grupo de Operadores de Red Españoles"
theme = "timer-hugo"

# We Used Ionicons Icon font for Icon, for more details check this link - https://ionicons.com/

# Site Menus
[menu]
    # Navbar Menus
    [[menu.nav]]
        name    = "About"
        url     = "/about"
        weight  = 2
    [[menu.nav]]
        name    = "Service"
        url     = "/service"
        weight  = 3
    [[menu.nav]]
        name    = "Gallery"
        url     = "/gallery"
        weight  = 4
    [[menu.nav]]
        name    = "Blog"
        url     = "/blog"
        weight  = 5
    [[menu.nav]]
        name    = "Contact"
        url     = "/contact"
        weight  = 6

# Site Params
[params]
    home = "Home"
    logo = "images/logo-esnog.png"
    dateFormat = "6 January 2006"

    # Banner Section
    [params.banner]
        enable  = true
        bgImage = "images/slider.jpg"
        heading = "HI, MY NAME IS ESNOG & I AM A"
        description = "WE STARTED TO MEET ON FEB. 2008, AND SINCE THEN WE GATHER WITH THE SPAIN´S NETWORK & INTERNET PROFESSIONALS TO SHARE OUR EXPERIENCES"
        btn     = true
        btnText = "View More"
        btnURL  = "https://esnog.net/"
        [[params.banner.flipText]]
            title   = "NETWORKING COMMUNITY"
        [[params.banner.flipText]]
            title   = "GROUP OF COLLEAGUES"
        [[params.banner.flipText]]
            title   = "TECHNICAL MESS"

    # Homepage About Section
    [params.about]
        enable  = true
        title   = "ABOUT ME"
        content = "ESNOG is an open forum for the exchange of technical information, operational experiences and engineering knowledge related to Internet infrastructure services with the aim of improving the exchange of experiences and information among engineers as well as increasing collaboration and coordination between networks in Spain."
        image   = "images/about/about.jpg"

    # Call to Action
    [params.cta]
        enable  = true
        title   = "SO WHAT YOU THINK ?"
        content = "ESNOG is open to all those involved in the industry of ISPs and Internet intrastructure services. Come in and Participate!"
        btnText = "Contact with me"
        btnURL  = "/contact"

    # Portfolio Section On Homepage
    [params.portfolio]
        enable  = true
        title   = "Latest Works"
        subtitle= "Her you can see the latest news and updates on activities related to ESNOG."

    # Feature Product Section
    [params.featureProduct]
        enable  = true
        title   = "SOME OF OUR FEATURES WORKS"
        subtitle= "Aliquam lobortis. Maecenas vestibulum mollis diam. Pellentesque auctor neque nec urna. Nulla sit amet est. Aenean posuere <br> tortor sed cursus feugiat, nunc augue blandit nunc, eu sollicitudin urna dolor sagittis lacus."

[params.googleApiFonts.family]
  tagsText        = [ "html", "body", "time" ]
  tagsHeading     = [ "h1", "h2", "h3", "h4", "h5", "h6" ]
  tagsMono        = [ "pre", "code", "samp" ]
  fallbackText    = "html"
  fallbackHeading = "h1"
  fallbackMono    = "pre"

[params.googleApiFonts.family.html]
  sans-serif = "Poppins"
[params.googleApiFonts.family.time]
  cursive    = "Creepster"
[params.googleApiFonts.family.h1]
  sans-serif = "Days One"
[params.googleApiFonts.family.h3]
  cursive    = "Creepster"
[params.googleApiFonts.family.pre]
  monospace  = "Cousine"
[params.googleApiFonts.family.samp]
  sans-serif = "Roboto"    
